import { useEffect, useRef, useState, type MutableRefObject } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RotateCcw, Maximize2, Minimize2, MousePointer2, Box } from 'lucide-react';
import { Simulation } from '@/lib/simulation/engine';
import { BOX_DEPTH, BOX_WIDTH, IN_PATH, LOADER_DROP, LOADER_HOME, OUT_PATH, PICK_ENTRY, PICK_EXIT, PICK_LANE_Z, PICK_LOOP_ENTRY, PICK_LOOP_INFEED_PATH, PICK_LOOP_PATH, PICK_STATION_PATH, TROLLEY_CENTER, TROLLEY_COLUMNS, TROLLEY_ENTRY, TROLLEY_ROWS, TROLLEY_SLOT_PITCH, TRUCK_CENTER, stationLayout, trolleySlotPoint, type ConveyorPath, type Point } from '@/lib/simulation/layout';
import { ORDER_COLORS as COLORS, orderPosition, shippingLoaderPosition } from '@/lib/simulation/position';
export const STAGE_LABELS:Record<string,string>={inductionQueue:'Induction queue',induction:'Box forming',inbound:'Inbound conveyor',pickingLoop:'Passing / recirculation loop',toStation:'90° transfer to station',picking:'Picking',pickBlocked:'Leaving picking station',toMerge:'Station conveyor',mergeWaiting:'Waiting at merge deck',toPassing:'90° transfer to passing line',pickedLoop:'Picked box on passing loop',outbound:'Outbound conveyor',trolleyQueue:'Auto-stow trolley',manualLoading:'Manual truck loading',completed:'Shipment completed'};
export default function Scene({engineRef,revision,onSelect}:{engineRef:MutableRefObject<Simulation>;revision:number;onSelect:(id:number)=>void}){
  const host=useRef<HTMLDivElement>(null),wrapper=useRef<HTMLDivElement>(null),resetCamera=useRef<()=>void>(()=>{}),selectRef=useRef(onSelect);
  const [error,setError]=useState(''),[full,setFull]=useState(false),[ready,setReady]=useState(false);
  useEffect(()=>{selectRef.current=onSelect},[onSelect]);
  useEffect(()=>{const root=host.current;if(!root)return;let disposed=false,raf=0,stateTimer=0;let renderer:THREE.WebGLRenderer;
    try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{stateTimer=window.setTimeout(()=>setError('3D 화면에는 WebGL이 필요합니다. 브라우저의 하드웨어 가속을 확인하세요. 시뮬레이션과 KPI는 계속 사용할 수 있습니다.'),0);return()=>{disposed=true;window.clearTimeout(stateTimer)}}
    renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.setClearColor(0xbac5c6);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.setAttribute('aria-label','3D fulfillment center. Drag to rotate, scroll to zoom, click a box to inspect its order.');renderer.domElement.setAttribute('role','img');root.appendChild(renderer.domElement);
    const scene=new THREE.Scene();scene.fog=new THREE.Fog(0xbac5c6,112,195);const camera=new THREE.OrthographicCamera(-36,36,24,-24,.1,240);
    const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minZoom=.6;controls.maxZoom=2.8;controls.maxPolarAngle=Math.PI*.46;controls.minPolarAngle=.12;
    const fit=()=>{const w=Math.max(root.clientWidth,1),h=Math.max(root.clientHeight,1),aspect=w/h,halfH=Math.max(20,37/aspect),zoom=Math.min(1.32,Math.max(1.05,Math.min(halfH*2*aspect/56,halfH*2/34))),damping=controls.enableDamping;controls.enableDamping=false;camera.position.set(48.5,45.8,64);controls.target.set(3.5,.8,4);camera.zoom=zoom;camera.updateProjectionMatrix();controls.update();controls.enableDamping=damping};resetCamera.current=fit;
    scene.add(new THREE.HemisphereLight(0xf4fbff,0x536065,2.8));const sun=new THREE.DirectionalLight(0xfffaf1,3.2);sun.position.set(-20,45,22);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-48;sun.shadow.camera.right=48;sun.shadow.camera.top=34;sun.shadow.camera.bottom=-34;sun.shadow.normalBias=.04;scene.add(sun);
    const mats=new Map<number,THREE.MeshStandardMaterial>();function material(color:number){if(!mats.has(color))mats.set(color,new THREE.MeshStandardMaterial({color,roughness:.72,metalness:.1}));return mats.get(color)!}
    const unitBox=new THREE.BoxGeometry(1,1,1);const cylinder=new THREE.CylinderGeometry(1,1,1,10);const sphere=new THREE.SphereGeometry(1,12,8);
    function box(parent:THREE.Object3D,x:number,y:number,z:number,w:number,h:number,d:number,color:number,shadow=true){const m=new THREE.Mesh(unitBox,material(color));m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=shadow;m.receiveShadow=true;parent.add(m);return m;}
    function cyl(parent:THREE.Object3D,x:number,y:number,z:number,r:number,h:number,color:number){const m=new THREE.Mesh(cylinder,material(color));m.position.set(x,y,z);m.scale.set(r,h,r);m.castShadow=true;parent.add(m);return m;}
    const textures:THREE.Texture[]=[];const spriteMaterials:THREE.SpriteMaterial[]=[];
    function label(text:string,x:number,y:number,z:number,width=5,color='#35464c',bg='#eaf0ed'){const c=document.createElement('canvas');c.width=512;c.height=112;const ctx=c.getContext('2d')!;ctx.fillStyle=bg;ctx.fillRect(0,0,512,112);ctx.fillStyle=color;ctx.font='600 31px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,58);const tx=new THREE.CanvasTexture(c);tx.colorSpace=THREE.SRGBColorSpace;textures.push(tx);const sm=new THREE.SpriteMaterial({map:tx,depthTest:false,transparent:true});spriteMaterials.push(sm);const s=new THREE.Sprite(sm);s.position.set(x,y,z);s.scale.set(width,width*112/512,1);s.renderOrder=8;scene.add(s);return s;}
    const facilityCenterX=3,facilityWidth=64,facilityDepth=31.2,dockX=TRUCK_CENTER[0],truckHomeZ=TRUCK_CENTER[1];
    box(scene,facilityCenterX,-.5,0,facilityWidth,.8,facilityDepth,0x60757d);box(scene,facilityCenterX,-.06,0,facilityWidth-.2,.15,facilityDepth-.2,0xd9e0dc);
    const grid=new THREE.GridHelper(facilityWidth,64,0xa9b7b5,0xc5cfca);grid.position.set(facilityCenterX,.035,0);grid.scale.z=facilityDepth/facilityWidth;scene.add(grid);
    // Low perimeter walls preserve the full process view.
    box(scene,facilityCenterX,1.1,-15.5,facilityWidth,2.2,.22,0xe9eeeb);box(scene,-28.8,1.1,-4,.22,2.2,22.8,0xe9eeeb);
    for(const x of [-27,-15,-3,9,21,33]){box(scene,x,2,-15.2,.32,4,.38,0x8c9d9f);box(scene,x,0.18,-14.7,.7,.3,.7,0xeeb955);}
    function zone(x:number,z:number,w:number,d:number,color:number){box(scene,x,.035,z,w,.024,d,color,false);}
    const params=engineRef.current.params,stationLayouts=Array.from({length:params.workers},(_,i)=>stationLayout(i,params.workers));
    zone(-19.2,2,7,9,0xc2cfbc);zone(TROLLEY_CENTER[0],3.7,8.4,12,0xc6d5d7);
    const zoneColors=[0xcbd8d2,0xc4dccd,0xddd6c7,0xc9dadd,0xdccddd,0xd8d9be];
    stationLayouts.forEach((station,i)=>zone(station.zoneCenter,-6,station.zoneWidth-.6,10.5,zoneColors[i%zoneColors.length]));
    for(let x=-27;x<34;x+=1.3){box(scene,x,.065,14.4,.7,.035,.12,0xe7bd55,false)}
    function conveyor(path:ConveyorPath,roller=false,width=1.05){for(let i=0;i<path.length-1;i++){const [ax,az]=path[i],[bx,bz]=path[i+1];const length=Math.hypot(bx-ax,bz-az),g=new THREE.Group();g.position.set((ax+bx)/2,0,(az+bz)/2);g.rotation.y=-Math.atan2(bz-az,bx-ax);scene.add(g);
      box(g,0,.84,0,length,.28,width+.16,0x65767b);box(g,0,1.015,0,length,.08,width,0x405357);for(const side of [-1,1])box(g,0,1.08,side*(width/2+.07),length,.11,.06,0xbdc9c6);
      for(let j=-length/2+.25;j<length/2;j+=roller?.34:.8){if(roller){const m=cyl(g,j,1.05,0,.075,width,0xaebcbd);m.rotation.x=Math.PI/2;}else box(g,j,1.065,0,.035,.012,width,0x657f7f,false);}
      for(let j=-length/2+.5;j<length/2;j+=2){for(const side of [-1,1]){box(g,j,.4,side*.4,.09,.8,.09,0x6e7f84);box(g,j,.06,side*.4,.24,.07,.24,0x7b8d90);}}
    }}
    type DeckKind='transfer'|'turn'|'merge'|'sorter'|'stow';
    const deckKeys=new Set<string>();
    function transferDeck(point:Point,kind:DeckKind='transfer'){const [x,z]=point,omni=kind==='turn'||kind==='merge'||kind==='sorter';box(scene,x,1.085,z,1,.13,1,kind==='sorter'?0x527b83:0x6e8f91);
      if(omni){for(const dx of [-.27,0,.27])for(const dz of [-.27,0,.27])cyl(scene,x+dx,1.17,z+dz,.065,.045,0xc5d0ce);}
      else for(let offset=-.32;offset<=.32;offset+=.16)box(scene,x,1.165,z+offset,.78,.035,.055,0xc5d0ce,false);
      for(const side of [-1,1])box(scene,x+side*.46,1.19,z,.055,.1,.98,0xe6ba49);
      if(kind==='merge'||kind==='sorter'){const blade=box(scene,x,1.245,z,.72,.055,.06,kind==='sorter'?0x58b8c4:0xe6ba49);blade.rotation.y=kind==='sorter'?-.55:.55;}
      const lampColor=kind==='sorter'?0x49c7d2:kind==='merge'?0xf0ba46:0x7bd957;cyl(scene,x+(kind==='merge' ? .34 : -.34),1.34,z+(kind==='sorter' ? .34 : -.34),.065,.14,lampColor);
    }
    function deckOnce(point:Point,kind:DeckKind='transfer'){const key=`${point[0].toFixed(4)},${point[1].toFixed(4)}`;if(deckKeys.has(key))return;deckKeys.add(key);transferDeck(point,kind);}
    function addCornerDecks(path:ConveyorPath,closed=false){const points=closed&&path.length>1&&path[0][0]===path.at(-1)![0]&&path[0][1]===path.at(-1)![1]?path.slice(0,-1):path;const first=closed?0:1,last=closed?points.length:points.length-1;
      for(let i=first;i<last;i++){const previous=points[(i-1+points.length)%points.length],point=points[i],next=points[(i+1)%points.length];const incoming:[number,number]=[point[0]-previous[0],point[1]-previous[1]],outgoing:[number,number]=[next[0]-point[0],next[1]-point[1]];if(Math.abs(incoming[0]*outgoing[1]-incoming[1]*outgoing[0])>1e-9)deckOnce(point,'turn');}}
    conveyor(IN_PATH,true);conveyor(OUT_PATH,false);conveyor(PICK_LOOP_INFEED_PATH,true,.85);
    conveyor(PICK_LOOP_PATH,true,.85);conveyor(PICK_STATION_PATH,true,.85);
    const infeedA=PICK_LOOP_INFEED_PATH[0],infeedB=PICK_LOOP_INFEED_PATH[1],infeedLength=Math.hypot(infeedB[0]-infeedA[0],infeedB[1]-infeedA[1]);for(const side of [-1,1])box(scene,(infeedA[0]+infeedB[0])/2,1.19,(infeedA[1]+infeedB[1])/2+side*.49,infeedLength,.045,.07,0xe9ac5b,false);
    deckOnce(PICK_LOOP_ENTRY,'merge');deckOnce(PICK_EXIT,'sorter');deckOnce(TROLLEY_ENTRY,'stow');addCornerDecks(IN_PATH);addCornerDecks(PICK_LOOP_PATH,true);
    stationLayouts.forEach((station,i)=>{const [x,z]=station.pick;conveyor([station.gate,station.stationEntry],true,.8);conveyor([station.stationExit,station.merge],true,.8);deckOnce(station.gate);deckOnce(station.stationEntry);deckOnce(station.stationExit);deckOnce(station.merge,'merge');const deskZ=z-1.12;box(scene,x,.7,deskZ,1.7,1.3,1.05,0x8a9e9f);box(scene,x,1.08,deskZ,1.8,.12,1.15,0xc7d2cd);box(scene,x+.68,1.75,deskZ-.34,.07,1.15,.08,0x566d70);box(scene,x+.68,2.03,deskZ-.34,.56,.4,.09,0x203338);box(scene,x+.68,2.03,deskZ-.28,.44,.27,.015,0xc6f367);label(`P${String(i+1).padStart(2,'0')}`,x,.4,PICK_LANE_Z-1.35,1.15,'#516564','#e3eae5');});
    // The 4 x 4 cage contains the real order meshes; no decorative box proxies are added.
    const trolleyWidth=(TROLLEY_COLUMNS-1)*TROLLEY_SLOT_PITCH+BOX_WIDTH+.3,trolleyDepth=(TROLLEY_ROWS-1)*TROLLEY_SLOT_PITCH+BOX_DEPTH+.3,trolley=new THREE.Group();trolley.position.set(TROLLEY_CENTER[0],0,TROLLEY_CENTER[1]);scene.add(trolley);
    box(trolley,0,.22,0,trolleyWidth,.18,trolleyDepth,0x52676c);for(const x of [-trolleyWidth/2,trolleyWidth/2])for(const z of [-trolleyDepth/2,trolleyDepth/2]){box(trolley,x,.62,z,.07,.8,.07,0x52676c);const wheel=cyl(trolley,x,.12,z,.12,.08,0x263b43);wheel.rotation.z=Math.PI/2;}
    for(const z of [-trolleyDepth/2,trolleyDepth/2])box(trolley,0,.72,z,trolleyWidth,.08,.07,0xe6ba49);for(const x of [-trolleyWidth/2,trolleyWidth/2])box(trolley,x,.72,0,.07,.08,trolleyDepth,0xe6ba49);
    for(let column=1;column<TROLLEY_COLUMNS;column++)box(trolley,(column-TROLLEY_COLUMNS/2)*TROLLEY_SLOT_PITCH,.34,0,.025,.06,trolleyDepth-.18,0x93a4a4,false);for(let row=1;row<TROLLEY_ROWS;row++)box(trolley,0,.34,(row-TROLLEY_ROWS/2)*TROLLEY_SLOT_PITCH,trolleyWidth-.18,.06,.025,0x93a4a4,false);
    const gantryEndX=TROLLEY_CENTER[0]+trolleyWidth/2+.08;box(scene,(TROLLEY_ENTRY[0]+gantryEndX)/2,1.95,TROLLEY_ENTRY[1],gantryEndX-TROLLEY_ENTRY[0]+.18,.1,.14,0x587277);for(const x of [TROLLEY_ENTRY[0],gantryEndX])box(scene,x,1.25,TROLLEY_ENTRY[1],.1,1.45,.1,0x587277);
    // Racks: two aisles, three shelf levels, SKU bins and pick-to-light modules.
    for(let i=0;i<params.racks;i++){const col=i%5,row=Math.floor(i/5),cell=(PICK_EXIT[0]-PICK_ENTRY[0])/5,x=PICK_ENTRY[0]+(col+.5)*cell,z=-6-row*4.1;const width=Math.min(4.5,cell-.6);
      for(const dx of [-width/2,width/2])for(const dz of [-.65,.65])box(scene,x+dx,2.0,z+dz,.105,4.0,.105,0x476d81);
      for(const h of [.35,1.5,2.65,3.8]){box(scene,x,h,z,width,.12,1.5,0x759497);box(scene,x,h+.12,z+.76,width,.15,.065,0xd7ad58);for(let n=0;n<4;n++){const binX=x-width/2+(n+.5)*width/4;box(scene,binX,h+.46,z,.68,.55,1.07,(i+n)%3===0?0x77a4a9:0xaac1bc);box(scene,binX,h+.44,z+.55,.28,.16,.018,0xe3e9dc);box(scene,binX,h+.16,z+.805,.2,.085,.025,(i+n)%4===0?0xc6f367:0x607b79);}}
      label(`R${String(i+1).padStart(2,'0')}`,x,4.2,z,1.35,'#eaf0ed','#496a77');}
    // Box erector with enclosure and cardboard magazine.
    box(scene,-17,.68,4,2.6,1.3,2.2,0x69878a);box(scene,-17,2.1,4,2.6,.2,2.2,0x94aaa8);for(const dx of [-1.15,1.15])for(const dz of [-.95,.95])box(scene,-17+dx,1.6,4+dz,.08,1.1,.08,0x51676c);
    box(scene,-17,1.65,5.06,2.3,.68,.04,0xb4c9c6);box(scene,-18.45,1.1,4,.25,.7,.55,0x314c55);box(scene,-18.59,1.18,4,.02,.25,.36,0xc6f367);
    for(let i=0;i<9;i++)box(scene,-19.2,.4+i*.09,5.1,1.3,.06,1.1,0xb98d5e);box(scene,-17.7,2.32,4,.14,.26,.14,0xc6f367);
    for(let x=-20.8;x<-18;x+=1.15){box(scene,x,.16,-1.8,.95,.2,1.5,0xa78e6a);for(let j=0;j<2;j++)box(scene,x,.5+j*.6,-1.8,.8,.56,1.25,0xc3a270);}
    // Manual shipping apron: trolley-to-truck travel is on foot, never on a conveyor.
    box(scene,dockX,.05,5.75,5.2,.04,2.6,0x879b9d);for(const dx of [-2.55,2.55]){box(scene,dockX+dx,1.75,5.75,.18,3.5,.2,0x647b80);box(scene,dockX+dx,.48,4.65,.3,.95,.3,0xd7af52);}
    const truck=new THREE.Group();truck.position.set(dockX,0,truckHomeZ);scene.add(truck);
    // Open cargo shell makes the rear door and hand-loaded box movement readable.
    box(truck,0,.55,0,3.1,.2,4.4,0xd5dedb);box(truck,0,2.85,0,3.1,.18,4.4,0xd5dedb);for(const side of [-1,1])box(truck,side*1.48,1.7,0,.14,2.3,4.4,0xd5dedb);box(truck,0,1.7,2.15,3.1,2.3,.12,0xd5dedb);
    box(truck,0,.6,.6,3,.4,6,0x4f626c);box(truck,0,1.28,3.0,3.0,1.9,2,0x4e8290);box(truck,0,1.72,4.02,2.58,.8,.04,0x344f5a);box(truck,0,.78,4.07,3,.24,.15,0x9aabad);for(const side of [-1,1]){for(const z of [-1.35,2.65]){const wh=cyl(truck,side*1.5,.5,z,.48,.3,0x263b43);wh.rotation.z=Math.PI/2;const hub=cyl(truck,side*1.68,.5,z,.24,.03,0x9cadae);hub.rotation.z=Math.PI/2;}box(truck,side*1.05,.93,4.1,.42,.22,.05,0xe8eacb);}
    const rearDoor=box(truck,0,2.68,-2.24,2.72,1.82,.08,0x9aabad),liftPivot=new THREE.Group();liftPivot.position.set(0,.58,-2.2);truck.add(liftPivot);box(liftPivot,0,0,-.48,2.7,.11,.96,0xe0b64e);
    const workerModels:THREE.Group[]=[];
    stationLayouts.forEach(station=>{const g=new THREE.Group();g.position.set(station.pick[0],0,station.pick[1]-2.05);scene.add(g);box(g,-.17,.45,0,.22,.8,.23,0x344e5a);box(g,.17,.45,0,.22,.8,.23,0x344e5a);box(g,0,1.11,0,.61,.6,.35,0xe2bc59);box(g,0,1.3,.18,.32,.17,.02,0xe1e7d6);const head=new THREE.Mesh(sphere,material(0xd4b48d));head.position.y=1.65;head.scale.set(.24,.27,.24);g.add(head);cyl(g,0,1.84,0,.29,.13,0xe7eee0);box(g,-.39,1.1,.09,.18,.57,.2,0xd1b18d);box(g,.39,1.1,.09,.18,.57,.2,0xd1b18d);workerModels.push(g);});
    type LoaderRig={group:THREE.Group;leftArm:THREE.Mesh;rightArm:THREE.Mesh;leftLeg:THREE.Mesh;rightLeg:THREE.Mesh};
    const shippingLoaderModels:LoaderRig[]=LOADER_HOME.map((home,index)=>{const group=new THREE.Group();group.position.set(home[0],0,home[1]);scene.add(group);const leftLeg=box(group,-.17,.45,0,.22,.8,.23,0x263b43),rightLeg=box(group,.17,.45,0,.22,.8,.23,0x263b43);box(group,0,1.11,0,.64,.62,.37,0xd9ed3f);box(group,0,1.18,.195,.58,.09,.018,0xe8eee8,false);box(group,0,1.02,.195,.58,.09,.018,0xe8eee8,false);const head=new THREE.Mesh(sphere,material(0xd4b48d));head.position.y=1.67;head.scale.set(.24,.27,.24);group.add(head);cyl(group,0,1.87,0,.3,.14,index?0xf2c84b:0xe7eee0);const leftArm=box(group,-.42,1.12,.08,.18,.6,.2,0xd9ed3f),rightArm=box(group,.42,1.12,.08,.18,.6,.2,0xd9ed3f);return {group,leftArm,rightArm,leftLeg,rightLeg};});
    label('01  INDUCTION',-18.1,.9,8,5.5);label('DPS  RECIRCULATION LOOP',(PICK_ENTRY[0]+PICK_EXIT[0])/2,.55,4.7,6.2,'#3f5558','#dce6df');label('02  DIGITAL PICKING',(PICK_ENTRY[0]+PICK_EXIT[0])/2,5.5,-10.7,7);label('03  OUTBOUND',(PICK_EXIT[0]+TROLLEY_ENTRY[0])/2,.55,1.45,4.2);label('16-SLOT  AUTO-STOW',TROLLEY_CENTER[0],2.35,-1.9,4.9);label('04  MANUAL SHIPPING',dockX+2.4,4.2,5.3,5.2);
    const crateGeo=new THREE.BoxGeometry(BOX_WIDTH,.49,BOX_DEPTH),crateMaterials=new Map<number,THREE.MeshStandardMaterial>();for(const color of Object.values(COLORS))crateMaterials.set(color,new THREE.MeshStandardMaterial({color,roughness:.7}));
    const boxes=new Map<number,THREE.Group>(),clickTargets:THREE.Object3D[]=[];const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let downX=0,downY=0;
    const down=(ev:PointerEvent)=>{downX=ev.clientX;downY=ev.clientY};const click=(ev:PointerEvent)=>{if(Math.hypot(ev.clientX-downX,ev.clientY-downY)>5)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((ev.clientX-rect.left)/rect.width*2-1,-(ev.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(clickTargets,false)[0];if(hit)selectRef.current(hit.object.userData.orderId);};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',click);
    function resize(){if(disposed)return;const w=root!.clientWidth,h=root!.clientHeight;renderer.setSize(w,h,false);const aspect=w/Math.max(1,h),halfH=Math.max(20,37/aspect);camera.left=-halfH*aspect;camera.right=halfH*aspect;camera.top=halfH;camera.bottom=-halfH;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(root);resize();fit();
    function animate(){if(disposed)return;const e=engineRef.current;const visible=new Set<number>();for(const o of e.orders.values()){if(o.stage==='completed')continue;if(o.stage==='inductionQueue'&&e.inductionQueue.indexOf(o.id)>=24)continue;visible.add(o.id);let g=boxes.get(o.id);const p=orderPosition(o,e);if(!g){g=new THREE.Group();const crate=new THREE.Mesh(crateGeo,crateMaterials.get(p.color));crate.castShadow=true;crate.userData.orderId=o.id;g.add(crate);const tape=new THREE.Mesh(unitBox,material(0xe8dfbf));tape.scale.set(.11,.012,.53);tape.position.y=.251;g.add(tape);box(g,.16,.05,.264,.17,.16,.01,0xe6eee7,false);scene.add(g);boxes.set(o.id,g);clickTargets.push(crate);}g.position.set(p.x,p.y,p.z);(g.children[0] as THREE.Mesh).material=crateMaterials.get(p.color)!;}
      for(const [id,g] of boxes)if(!visible.has(id)){scene.remove(g);boxes.delete(id);const idx=clickTargets.indexOf(g.children[0]);if(idx>=0)clickTargets.splice(idx,1);}
      workerModels.forEach((g,i)=>{const w=e.workers[i];g.rotation.y=w?.phase==='picking'?Math.sin(e.time*.13+i)*.22:0;const arm=g.children[g.children.length-1];arm.rotation.x=w?.phase==='picking'?-.5+Math.sin(e.time*.8)*.3:0;});
      shippingLoaderModels.forEach((rig,index)=>{const projected=shippingLoaderPosition(index,e),loader=e.shippingLoaders[index];rig.group.position.set(projected.x,0,projected.z);let target=LOADER_HOME[index]??LOADER_HOME[0];if(loader?.phase==='loading')target=projected.carrying?(LOADER_DROP[index]??LOADER_DROP[0]):trolleySlotPoint(loader.trolleySlot);const dx=target[0]-projected.x,dz=target[1]-projected.z;if(Math.hypot(dx,dz)>.02)rig.group.rotation.y=Math.atan2(dx,dz);
        const walking=loader?.phase!=='idle',stride=walking?Math.sin((e.time-(loader?.phaseAt??0))*5)*.28:0,reach=projected.carrying?-1.05:loader?.phase==='loading'?-.42:walking?-.12:0;rig.leftLeg.rotation.x=stride;rig.rightLeg.rotation.x=-stride;rig.leftArm.rotation.x=reach-stride*.45;rig.rightArm.rotation.x=reach+stride*.45;});
      const doorTarget=e.truckAvailable?2.68:1.7;rearDoor.position.y+=(doorTarget-rearDoor.position.y)*.14;const liftTarget=e.truckAvailable?0:Math.PI/2;liftPivot.rotation.x+=(liftTarget-liftPivot.rotation.x)*.14;
      const departure=e.truckAvailable?0:Math.min(16,(e.time-e.truckAwayAt)*.5);truck.position.z=truckHomeZ+departure;truck.visible=e.truckAvailable||departure<15;controls.update();renderer.render(scene,camera);raf=requestAnimationFrame(animate);}
    animate();stateTimer=window.setTimeout(()=>{if(!disposed){setError('');setReady(true)}},0);
    return ()=>{disposed=true;window.clearTimeout(stateTimer);cancelAnimationFrame(raf);observer.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointerup',click);unitBox.dispose();cylinder.dispose();sphere.dispose();crateGeo.dispose();mats.forEach(m=>m.dispose());crateMaterials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());spriteMaterials.forEach(m=>m.dispose());grid.geometry.dispose();(grid.material as THREE.Material).dispose();renderer.dispose();renderer.domElement.remove();};
  },[revision,engineRef]);
  useEffect(()=>{const fn=()=>setFull(document.fullscreenElement===wrapper.current);document.addEventListener('fullscreenchange',fn);return()=>document.removeEventListener('fullscreenchange',fn)},[]);
  const toggleFull=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await wrapper.current?.requestFullscreen();}catch{setFull(v=>!v)}};
  return <div ref={wrapper} className={`scene-wrap ${full?'scene-fullscreen':''}`}><div ref={host} className="scene-canvas"/>{(!ready||error)&&<div className="scene-message"><Box size={28}/><p>{error||'3D 설비를 불러오는 중입니다.'}</p></div>}<div className="scene-top-label"><span className="scene-dot"/> LIVE MODEL <span className="scene-label-divider"/> 1 ORDER = 1 BOX</div><div className="camera-tools"><button onClick={()=>resetCamera.current()} title="Reset camera" aria-label="Reset camera"><RotateCcw size={16}/></button><button onClick={toggleFull} title="Fullscreen" aria-label="Fullscreen">{full?<Minimize2 size={16}/>:<Maximize2 size={16}/>}</button></div><div className="scene-hint"><MousePointer2 size={13}/> Drag to orbit · Scroll to zoom · Click a box</div><div className="scene-legend">{[['#e9ac5b','Waiting'],['#42a4b5','Moving'],['#c6f367','Picking'],['#a5a0de','Shipping']].map(([c,t])=><span key={t}><i style={{background:c}}/>{t}</span>)}</div></div>;
}
